[package]
name = "easybreach_bloom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bloomfilter = "1.*"
bincode = { version = "1.*"}
anyhow = "1.0.100"
serde = "1.*"
serde_derive = "1.*"