[package]
name = "easybreach_bloom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bloomfilter = "2.0.0"
bincode = { version = "1.*"}
anyhow = "1.*"
serde = "1.0.228"
serde_derive = "1.0.228"