on:
  push:
    tags:
      - 'v*.*.*'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

name: compile

jobs:

  build:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        container:
          - { os: 'ubuntu-latest', rust_target: 'aarch64-unknown-linux-musl' }
          - { os: 'ubuntu-latest', rust_target: 'x86_64-unknown-linux-musl' }
          - { os: 'macos-latest', rust_target: 'x86_64-apple-darwin' }
          - { os: 'macos-latest', rust_target: 'aarch64-apple-darwin' }
    runs-on: "${{ matrix.container.os }}"
    steps:
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          toolchain: stable
          target: "${{ matrix.container.rust_target }}"
          override: true
      - uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1
        with:
          use-cross: true
          command: build
          args: "--release --target ${{ matrix.container.rust_target }}"
      - name: List target
        run: |
          ls -lah target/${{ matrix.container.rust_target }}/release
      - name: Build and push
        run: |
          cp target/${{ matrix.container.rust_target }}/release/easybreach target/${{ matrix.container.rust_target }}/release/easybreach_${{ matrix.container.rust_target }}
          cp target/${{ matrix.container.rust_target }}/release/downloader target/${{ matrix.container.rust_target }}/release/downloader_${{ matrix.container.rust_target }}
      - name: Prepare output artifact (easybreach)
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: easybreach-${{ matrix.container.rust_target }}
          path: |
            target/${{ matrix.container.rust_target }}/release/easybreach_${{ matrix.container.rust_target }}
            target/${{ matrix.container.rust_target }}/release/downloader_${{ matrix.container.rust_target }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - name: download artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          path: binaries
      - name: Release
        uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090 # v2
        with:
          fail_on_unmatched_files: true
          files: |
            binaries/*/*

  docker_build:
    name: docker
    runs-on: ubuntu-latest
    needs: ["build"]
    strategy:
      fail-fast: true
      matrix:
        container:
          - { os: 'ubuntu-latest', arch: 'arm64', rust_target: 'aarch64-unknown-linux-musl' }
          - { os: 'ubuntu-latest', arch: 'amd64', rust_target: 'x86_64-unknown-linux-musl' }
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2
        id: buildx
        with:
          install: true
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: download artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          path: binaries

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@d7543c93d881b35a8faa02e8e3605f69b7a1ce62 # v3.10.0
        with:
          cosign-release: 'v2.1.0'
      - name: Check install!
        run: cosign version

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  docker_manifest:
    name: Docker Image
    runs-on: ubuntu-latest
    needs: ["docker_build"]
    steps:
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@d7543c93d881b35a8faa02e8e3605f69b7a1ce62 # v3.10.0
        with:
          cosign-release: 'v2.1.0'
      - name: Check install!
        run: cosign version

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push manifest
        run: |
          docker manifest create dragonsecurity/easybreach:${{github.ref_name}} dragonsecurity/easybreach:${{github.ref_name}}_amd64 dragonsecurity/easybreach:${{github.ref_name}}_arm64
          docker manifest push dragonsecurity/easybreach:${{github.ref_name}}